[platformio]
src_dir = SolarBridge-Matrix

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
lib_deps =
	tzapu/WiFiManager@^2.0.17
	bblanchon/ArduinoJson@^6.21.5
	majicdesigns/MD_MAX72xx@^3.5.1
	majicdesigns/MD_Parola@^3.7.3
build_flags =
	-DPIO_BUILD=1
