[platformio]
src_dir = MatrixDiagnostic

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM7
monitor_port = COM7
lib_deps =
	majicdesigns/MD_MAX72xx@^3.5.1
	majicdesigns/MD_Parola@^3.7.3
